name: WhisperNotice
main: kr.jjory.whispernotice.WhisperNotice
version: 1.0.0
api-version: 1.13
author: jjory
website: https://github.com/jojoRy/WhisperNotice

commands:
  공지:
    description: 모든 플레이어에게 공지를 보냅니다.
    permission: op
    aliases: [broadcast]
  공지변환:
    description: config.yml을 수정후 리로드 합니다.
    permission: op
  귓속말:
    description: 귓속말을 보냅니다.
  귓속:
    description: 귓속말을 보냅니다.
  귓:
    description: 귓속말을 보냅니다.